import fs from "fs";
const LANGS = ["en_US","zh_Hans_CN","zh_Hant_HK","ja_JP","ko_KR","de_DE","es_ES","fr_FR","it_IT","pl_PL","pt_BR","ru_RU"];
const T = {
  PROFILE_CUSTOM:            ["Custom (per-age)","自定义（分时代）","自訂（分時代）","カスタム（時代別）","사용자 지정(시대별)","Benutzerdefiniert (pro Ära)","Personalizado (por era)","Personnalisé (par ère)","Personalizzato (per era)","Niestandardowy (na erę)","Personalizado (por era)","Свой (по эпохам)"],
  PROFILE_CUSTOM_DESC:       ["Set each age's length independently using the per-age options below.","使用下方的分时代选项独立设置每个时代的长度。","使用下方的分時代選項獨立設定每個時代的長度。","下の時代別オプションで各時代の長さを個別に設定します。","아래 시대별 옵션으로 각 시대 길이를 개별 설정합니다.","Lege die Länge jeder Ära separat über die Optionen unten fest.","Define la duración de cada era por separado con las opciones de abajo.","Définissez la durée de chaque ère séparément avec les options ci-dessous.","Imposta la durata di ogni era separatamente con le opzioni qui sotto.","Ustaw długość każdej ery osobno za pomocą opcji poniżej.","Defina a duração de cada era separadamente nas opções abaixo.","Задайте длину каждой эпохи отдельно с помощью параметров ниже."],
  ANTIQUITY_LENGTH_NAME:     ["Eras+ Antiquity Length","Eras+ 远古时代长度","Eras+ 遠古時代長度","Eras+ 古代の長さ","Eras+ 고대 길이","Eras+ Länge der Antike","Eras+ Duración de la Antigüedad","Eras+ Durée de l'Antiquité","Eras+ Durata dell'Antichità","Eras+ Długość starożytności","Eras+ Duração da Antiguidade","Eras+ Длина Античности"],
  ANTIQUITY_LENGTH_DESC:     ["Antiquity age length when Eras+ Pacing is set to Custom.","当 Eras+ 节奏设为自定义时的远古时代长度。","當 Eras+ 節奏設為自訂時的遠古時代長度。","Eras+ ペースがカスタムのときの古代の長さ。","Eras+ 페이스가 사용자 지정일 때 고대 길이입니다.","Länge der Antike, wenn Eras+ Tempo auf Benutzerdefiniert steht.","Duración de la Antigüedad cuando el ritmo de Eras+ es Personalizado.","Durée de l'Antiquité quand le rythme Eras+ est Personnalisé.","Durata dell'Antichità quando il ritmo di Eras+ è Personalizzato.","Długość starożytności, gdy tempo Eras+ jest Niestandardowe.","Duração da Antiguidade quando o ritmo do Eras+ é Personalizado.","Длина Античности, когда темп Eras+ задан как Свой."],
  EXPLORATION_LENGTH_NAME:   ["Eras+ Exploration Length","Eras+ 探索时代长度","Eras+ 探索時代長度","Eras+ 探索の長さ","Eras+ 탐험 길이","Eras+ Länge der Erkundung","Eras+ Duración de la Exploración","Eras+ Durée de l'Exploration","Eras+ Durata dell'Esplorazione","Eras+ Długość eksploracji","Eras+ Duração da Exploração","Eras+ Длина Освоения"],
  EXPLORATION_LENGTH_DESC:   ["Exploration age length when Eras+ Pacing is set to Custom.","当 Eras+ 节奏设为自定义时的探索时代长度。","當 Eras+ 節奏設為自訂時的探索時代長度。","Eras+ ペースがカスタムのときの探索の長さ。","Eras+ 페이스가 사용자 지정일 때 탐험 길이입니다.","Länge der Erkundung, wenn Eras+ Tempo auf Benutzerdefiniert steht.","Duración de la Exploración cuando el ritmo de Eras+ es Personalizado.","Durée de l'Exploration quand le rythme Eras+ est Personnalisé.","Durata dell'Esplorazione quando il ritmo di Eras+ è Personalizzato.","Długość eksploracji, gdy tempo Eras+ jest Niestandardowe.","Duração da Exploração quando o ritmo do Eras+ é Personalizado.","Длина Освоения, когда темп Eras+ задан как Свой."],
  MODERN_LENGTH_NAME:        ["Eras+ Modern Length","Eras+ 现代时代长度","Eras+ 現代時代長度","Eras+ 近代の長さ","Eras+ 현대 길이","Eras+ Länge der Moderne","Eras+ Duración de la Era Moderna","Eras+ Durée de l'ère Moderne","Eras+ Durata dell'Era Moderna","Eras+ Długość ery nowożytnej","Eras+ Duração da Era Moderna","Eras+ Длина Современности"],
  MODERN_LENGTH_DESC:        ["Modern age length when Eras+ Pacing is set to Custom.","当 Eras+ 节奏设为自定义时的现代时代长度。","當 Eras+ 節奏設為自訂時的現代時代長度。","Eras+ ペースがカスタムのときの近代の長さ。","Eras+ 페이스가 사용자 지정일 때 현대 길이입니다.","Länge der Moderne, wenn Eras+ Tempo auf Benutzerdefiniert steht.","Duración de la Era Moderna cuando el ritmo de Eras+ es Personalizado.","Durée de l'ère Moderne quand le rythme Eras+ est Personnalisé.","Durata dell'Era Moderna quando il ritmo di Eras+ è Personalizzato.","Długość ery nowożytnej, gdy tempo Eras+ jest Niestandardowe.","Duração da Era Moderna quando o ritmo do Eras+ é Personalizado.","Длина Современности, когда темп Eras+ задан как Свой."],
};
const tag = (k) => `LOC_MOD_ERAS_PLUS_${k}`;
const enRows = Object.keys(T).map((k) => `    <Row Tag="${tag(k)}" Language="en_US">\n      <Text>${T[k][0]}</Text>\n    </Row>`).join("\n");
let l10nRows = "";
for (const k of Object.keys(T)) for (let i = 1; i < LANGS.length; i++) l10nRows += `    <Replace Tag="${tag(k)}" Language="${LANGS[i]}"><Text>${T[k][i]}</Text></Replace>\n`;
const enPath = "content/text/en_us/ErasPlusText.xml", l10nPath = "content/l10n/ErasPlusText.xml";
let en = fs.readFileSync(enPath, "utf8"), l10n = fs.readFileSync(l10nPath, "utf8");
fs.writeFileSync(enPath, en.replace("  </LocalizedText>", `${enRows}\n  </LocalizedText>`));
fs.writeFileSync(l10nPath, l10n.replace("  </LocalizedText>", `${l10nRows}  </LocalizedText>`));
console.log(`en_US +${Object.keys(T).length} rows; l10n +${Object.keys(T).length*(LANGS.length-1)} replaces`);
